### ISSUE TITLE
Backend validations

### ISSUE THREAD

**Issue by someotherkyle** [FIS-CBM/dog-park-locator#25]
Currently info and website are required, zipcode accepts letters & symbols.

**Comment by someotherkyle** [comment]
also unique names. what if there were a "chain" of dog parks run by the same folks... eg Petco has 4 dog parks with no unique name, just off of street address

**Comment by jhharwood88** [comment]
I had completely forgot about this project lol, not sure if anyone will see this but how y’all doin? My slack client on my phone got messed up when I set up my work groups. If y’all are still in the group, would love to get a link to join back in
